coverage:
  status:
    project:
      default:
        # https://docs.codecov.com/docs/commit-status#target
        target: 80%
        informational: true
    # https://docs.codecov.com/docs/commit-status#patch-status
    patch:
      default:
        target: 80%

# https://docs.codecov.com/docs/pull-request-comments#disable-comment
comment: false
