/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubeedge/kubeedge/pkg/apis/policy/v1alpha1"
	scheme "github.com/kubeedge/kubeedge/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AccessMixersGetter has a method to return a AccessMixerInterface.
// A group's client should implement this interface.
type AccessMixersGetter interface {
	AccessMixers(namespace string) AccessMixerInterface
}

// AccessMixerInterface has methods to work with AccessMixer resources.
type AccessMixerInterface interface {
	Create(ctx context.Context, accessMixer *v1alpha1.AccessMixer, opts v1.CreateOptions) (*v1alpha1.AccessMixer, error)
	Update(ctx context.Context, accessMixer *v1alpha1.AccessMixer, opts v1.UpdateOptions) (*v1alpha1.AccessMixer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AccessMixer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AccessMixerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessMixer, err error)
	AccessMixerExpansion
}

// accessMixers implements AccessMixerInterface
type accessMixers struct {
	client rest.Interface
	ns     string
}

// newAccessMixers returns a AccessMixers
func newAccessMixers(c *PolicyV1alpha1Client, namespace string) *accessMixers {
	return &accessMixers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the accessMixer, and returns the corresponding accessMixer object, and an error if there is any.
func (c *accessMixers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccessMixer, err error) {
	result = &v1alpha1.AccessMixer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("accessmixers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AccessMixers that match those selectors.
func (c *accessMixers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccessMixerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AccessMixerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("accessmixers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested accessMixers.
func (c *accessMixers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("accessmixers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a accessMixer and creates it.  Returns the server's representation of the accessMixer, and an error, if there is any.
func (c *accessMixers) Create(ctx context.Context, accessMixer *v1alpha1.AccessMixer, opts v1.CreateOptions) (result *v1alpha1.AccessMixer, err error) {
	result = &v1alpha1.AccessMixer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("accessmixers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessMixer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a accessMixer and updates it. Returns the server's representation of the accessMixer, and an error, if there is any.
func (c *accessMixers) Update(ctx context.Context, accessMixer *v1alpha1.AccessMixer, opts v1.UpdateOptions) (result *v1alpha1.AccessMixer, err error) {
	result = &v1alpha1.AccessMixer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("accessmixers").
		Name(accessMixer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessMixer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the accessMixer and deletes it. Returns an error if one occurs.
func (c *accessMixers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("accessmixers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *accessMixers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("accessmixers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched accessMixer.
func (c *accessMixers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessMixer, err error) {
	result = &v1alpha1.AccessMixer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("accessmixers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
