/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeedge/kubeedge/pkg/apis/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAccessMixers implements AccessMixerInterface
type FakeAccessMixers struct {
	Fake *FakePolicyV1alpha1
	ns   string
}

var accessmixersResource = schema.GroupVersionResource{Group: "policy.kubeedge.io", Version: "v1alpha1", Resource: "accessmixers"}

var accessmixersKind = schema.GroupVersionKind{Group: "policy.kubeedge.io", Version: "v1alpha1", Kind: "AccessMixer"}

// Get takes name of the accessMixer, and returns the corresponding accessMixer object, and an error if there is any.
func (c *FakeAccessMixers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccessMixer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(accessmixersResource, c.ns, name), &v1alpha1.AccessMixer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessMixer), err
}

// List takes label and field selectors, and returns the list of AccessMixers that match those selectors.
func (c *FakeAccessMixers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccessMixerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(accessmixersResource, accessmixersKind, c.ns, opts), &v1alpha1.AccessMixerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AccessMixerList{ListMeta: obj.(*v1alpha1.AccessMixerList).ListMeta}
	for _, item := range obj.(*v1alpha1.AccessMixerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested accessMixers.
func (c *FakeAccessMixers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(accessmixersResource, c.ns, opts))

}

// Create takes the representation of a accessMixer and creates it.  Returns the server's representation of the accessMixer, and an error, if there is any.
func (c *FakeAccessMixers) Create(ctx context.Context, accessMixer *v1alpha1.AccessMixer, opts v1.CreateOptions) (result *v1alpha1.AccessMixer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(accessmixersResource, c.ns, accessMixer), &v1alpha1.AccessMixer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessMixer), err
}

// Update takes the representation of a accessMixer and updates it. Returns the server's representation of the accessMixer, and an error, if there is any.
func (c *FakeAccessMixers) Update(ctx context.Context, accessMixer *v1alpha1.AccessMixer, opts v1.UpdateOptions) (result *v1alpha1.AccessMixer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(accessmixersResource, c.ns, accessMixer), &v1alpha1.AccessMixer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessMixer), err
}

// Delete takes name of the accessMixer and deletes it. Returns an error if one occurs.
func (c *FakeAccessMixers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(accessmixersResource, c.ns, name, opts), &v1alpha1.AccessMixer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAccessMixers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(accessmixersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AccessMixerList{})
	return err
}

// Patch applies the patch and returns the patched accessMixer.
func (c *FakeAccessMixers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessMixer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(accessmixersResource, c.ns, name, pt, data, subresources...), &v1alpha1.AccessMixer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessMixer), err
}
